### ISSUE TITLE
An error occurred (AccessDenied) when calling the AssumeRole operation

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#11]
`An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::9xxxxxxxxxx:assumed-role/AWS-Simple-CICD-TeamOne-vimpsvlncctestpipel-SP8VE3BYU66Q/AWSCodeBuild-c17e5754-c377-41e5-b1ca-7276e582aeee is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::0xxxxxxxxxx2:role/admin`

We have a landing zone account where my username is let's say "simi". I am able to assume role "admin" in accounts - dev, test, tools, and prod. 

As the documentation suggests: https://github.com/awslabs/aws-simple-cicd/blob/master/docs/admin.md#deploy-pipelines 

"If the AWS accounts are generated using AWS Landing Zone or Control Tower, then use the cross-account role generated by that service and skip this step.", I have skipped this step. 

The only change I have made is replaced ROLE_NAME=role/deployment-role
with

`ROLE_NAME=role/admin` 

in line 19 of https://github.com/awslabs/aws-simple-cicd/blob/master/scripts/assume-cross-account-role.env . 

Tried changing it to `ROLE_NAME=role/simi` as well

Is it required to make any additional changes to be able to resolve this error? How can this be fixed?

**Comment by srijitm** [comment]
The bug is here: https://github.com/awslabs/aws-simple-cicd/blob/master/lib/iam/code-build-role.ts on line 41. Please update it manually and deploy. I will start working on the fix.

**Comment by s1mrankaur** [comment]
@srijitm Thanks for your response. Alright. On line 41, I should be replacing `role/deployment-role` with  `role/simi`. Is that right?

**Comment by srijitm** [comment]
Yes. I will try push a fix for this early next week but for now that will work.

**Comment by srijitm** [comment]
You can now set the cross-account IAM role name in project-config.json
