### ISSUE TITLE
pipeline notifications through SNS

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#12]
What events in this pipeline should trigger a notification? I added a subscriber through the AWS console.  When I publish a message to the topic from the AWS console, I do get a notification. I haven't received any notification from the pipeline though. It seems like there is currently no event in the pipeline that triggers a notification as function `send_codebuild_events_to_sns` never really gets called. 

I would like to trigger the notification:

1. Whenever there is an error anywhere in the pipeline
2. When the master branch pipeline is approved or declined for prod. environment

The `send_build_events_to_sns` method expects a certain structure:

for ex:
```
    status = message['detail']['build-status']
    project = message['detail']['project-name']
    build_id = message['detail']['build-id']

```

3. Does this imply that it's required to create this message structure each time the method is triggered? Would be great to see an example of this.
4. If the subscriber email had to be configured in the ci/cd infrastructure as code instead of configuring it on AWS console, where should that go in this ci/cd implementation? Would be great to see a tiny example f it.

**Comment by srijitm** [comment]
I was unable to reproduce this on my side. Notifications are sent to SNS on every state change in the pipeline stages. I just did some tests and here are the emails I got:

**Email 1**
Project: acme-markets-roadrunner-rocket-powered-skates-master-build
Status: IN_PROGRESS
Build Id: arn:aws:codebuild:ca-central-1:628898779211:build/acme-markets-roadrunner-rocket-powered-skates-master-build:7aaae7a2-03e8-41f2-83c2-0d61cf45426b

**Email 2**
Project: acme-markets-roadrunner-rocket-powered-skates-master-build
Status: SUCCEEDED
Build Id: arn:aws:codebuild:ca-central-1:628898779211:build/acme-markets-roadrunner-rocket-powered-skates-master-build:7aaae7a2-03e8-41f2-83c2-0d61cf45426b

and so on for each stage in the pipeline.

Can you provide some more details on the pipeline and corresponding SNS topic you have provisioned in your account?

**Comment by srijitm** [comment]
@s1mrankaur Do you have any updates on this issue?

**Comment by s1mrankaur** [comment]
@srijitm  I have attached a snapshot of the pipeline. https://ibb.co/Hh3zjgy . I don't receive any emails unless I send a publish a message on the console. Is there any info/logs that I can share with you to debug this? @srijitm

**Comment by srijitm** [comment]
Can you execute the pipeline and share logs from the 'acme-markets-roadrunner-cicd-emailHandler' Lambda function? We need to check if the Lambda is being invoked. If it is then is it throwing any exceptions.

**Comment by s1mrankaur** [comment]
@srijitm I do not see email handler lambda function in the pipeline itself. The only lambda function I see is SemverLambda in the Build phase.  Also, I do not see a call to the function 'send_codebuild_events_to_sns' anywhere in the codebase which is probably the reason

**Comment by srijitm** [comment]
@s1mrankaur The pipeline doesn't have explicit calls to the emailHandler Lambda. CodeBuild emits events on EventBridge which in turns trigger EmailHandler. In your Lambda Console there will be a cicd-emailHandler Lambda function. 

![Screen Shot 2020-11-17 at 11 34 25 AM](https://user-images.githubusercontent.com/4087874/99418387-f988e280-28c8-11eb-980e-e194fc4c5ef3.png)

**Comment by s1mrankaur** [comment]
@srijitm  I do not see event bridge trigger for the lambda function. Attached snapshot: https://ibb.co/B3qjx8T  . where in code is the eventbridge trigger defined?

**Comment by srijitm** [comment]
It's here:

`
buildProject.onStateChange('deploymentStatus', {
      target: new targets.LambdaFunction(emailHandler)
    })

deployProject.onStateChange('deploymentStatus', {
        target: new targets.LambdaFunction(emailHandler)
      })

`

**Comment by srijitm** [comment]
Can you confirm that the emailHandler lambda is being triggered?

**Comment by s1mrankaur** [comment]
@srijitm  It's not being triggered. There is no trigger for the function itself.

**Comment by srijitm** [comment]
Can you check if the Event Rules show up in the cloudformation stack? See screnshot below:

![Screen Shot 2020-11-17 at 1 15 23 PM](https://user-images.githubusercontent.com/4087874/99430203-0a405500-28d7-11eb-993e-f949adae2654.png)

**Comment by s1mrankaur** [comment]
@srijitm Doesn't look like; 
![eventrules](https://user-images.githubusercontent.com/72841233/99430844-b9246700-28be-11eb-9131-1b70257c6e8a.PNG)

**Comment by srijitm** [comment]
Can you filter by 'events:rule'?

**Comment by s1mrankaur** [comment]
@srijitm 
![eventsrulefilter](https://user-images.githubusercontent.com/72841233/99432645-4963ab80-28c1-11eb-8f5a-282e7d214b79.PNG)

**Comment by srijitm** [comment]
If you follow the Physical ID links you should be routed to EventBridge. You should be able to see the integration with the lambda function. If it is missing, can you try deleting the re-deploying just the team stack?

![Screen Shot 2020-11-17 at 1 51 48 PM](https://user-images.githubusercontent.com/4087874/99433928-2d213800-28dc-11eb-9f5f-68e92a953917.png)

**Comment by s1mrankaur** [comment]
@srijitm I do see this:
![eventruleemail](https://user-images.githubusercontent.com/72841233/99440965-212d7a00-28cc-11eb-8dd4-d699c8fc0dc0.PNG)

I don't see event bridge as a trigger for lambda function though:

![emaillambda](https://user-images.githubusercontent.com/72841233/99441044-386c6780-28cc-11eb-9887-8883949f644e.PNG)

Also, the email is still not being triggered

**Comment by srijitm** [comment]
Changing the source repo shouldn't affect it. Maybe try deleting everything and re-deploying from scratch to see if that helps. It's really strange because the EventBridge rule is pointing to the Lambda function but Lambda isn't showing the trigger.

**Comment by s1mrankaur** [comment]
@srijitm   I did delete the entire stack and created it again. But the lambda function still didn't get a trigger. You can access the copy of code that I am running here at https://bitbucket.org/sikau/testcicd

**Comment by s1mrankaur** [comment]
@srijitm  I can see the invocations for the function now: This is what I have in the logs:
```


[ERROR] ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation: Traceback (most recent call last):  File "/var/task/lambda.py", line 39, in send_codebuild_events_to_sns    sns_topic = ssm.get_parameter(  File "/var/runtime/botocore/client.py", line 316, in _api_call    return self._make_api_call(operation_name, kwargs)  File "/var/runtime/botocore/client.py", line 635, in _make_api_call    raise error_class(parsed_response, operation_name) | [ERROR] ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation: Traceback (most recent call last):   File "/var/task/lambda.py", line 39, in send_codebuild_events_to_sns     sns_topic = ssm.get_parameter(   File "/var/runtime/botocore/client.py", line 316, in _api_call     return self._make_api_call(operation_name, kwargs)   File "/var/runtime/botocore/client.py", line 635, in _make_api_call     raise error_class(parsed_response, operation_name)
-- | --



```

**Comment by s1mrankaur** [comment]
@srijitm  Turns out the name of the key in SSM is again different. The key that exists is:

`/vaisala/vimps/vlncc/sns-topic/test-master-arn`

The key that lambda email-handler is looking for is:


/vaisala/vimps/vlncc/sns-topic/testpipeline-master-arn
--

Could you may be point out why is that?

test is the name of my coderepository that testcicd (cicd repo) is watching.  Here's the testcicd repo code:  https://bitbucket.org/sikau/testcicd

**Comment by srijitm** [comment]
Can you share the repository definition in your project-config.json?

**Comment by s1mrankaur** [comment]
@srijitm 

{
    "naming": {
      "company": "vaisala",
      "dept": "vimps",
      "project":  "vlncc"
    },
    "deployment": {
      "region": "us-west-2",
      "cicdRoleName": "deployment-role"
    },
    "accountIds": {
      "cicd": "123456782",
      "dev": "123456781",
      "test": "123456780",
      "prod": "123456783"
    },
    "teamOne": [
      {
        "pipelineName": "testpipeline", #if I change this to "test", it works okay
        "ccRepoName": "test",
        "branch": "master",
        "type": "BitBucket",
        "cron": ""
      }
    ]
    ],
    "sharedResources": {
      "cicdBucket": "cicd"    
    },
    "defaultRegions": {
      "cicd": "us-west-2",
      "dev": "us-west-2",
      "test": "us-west-2",
      "prod": "us-west-2"
    }
  }
Also, what  is 
```

   "sharedResources": {
      "cicdBucket": "cicd"    
    },
```

for?
