### ISSUE TITLE
Integrate AWS config to define rules in the pipeline and track configuration changes

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#20]
Feature request to integrate AWS config to define rules in the pipeline and track configuration changes

**Comment by srijitm** [comment]
Can you please describe the business use-case? 

You should be able to configure AWS Config rules to monitor CodePipeline/CodeBuild. I don't believe Config rules be set by this project, but rather the team that wants to monitor. You should be able to get all your changes via the git history. If users are making changes directly in the console it is likely a cultural challenge. You can of course limit their permissions.

Curious to hear more about this.

**Comment by s1mrankaur** [comment]
@srijitm  The use-case is continuous compliance. Correct me if I am wrong but I see it recommended to track configuration changes through the pipeline by the integration of AWS config. Also, https://aws.amazon.com/about-aws/whats-new/2018/09/aws-config-adds-support-for-aws-codepipeline

**Comment by s1mrankaur** [comment]
@srijitm Also, https://github.com/aws-samples/devsecops-workshop-on-aws  Here as well, Section "Continuous integration and evaluation of security controls" mentions AWS config and TaskCat, both I believe to be really useful additions to the pipeline.

**Comment by srijitm** [comment]
AWS Config allows you to monitor changes made to the configuration of the pipelines defined in CodePipeline e.g. artifact store, stage configuration, notifications etc. In this case the pipelines are defined using infrastructure as code (CDK). That means all updates to the pipelines should also be made using CDK and released like any other software development project. 

Are you looking to get notified if the pipelines themselves change or if someone deployed something using the pipeline which violated compliance? 

For the former, you can set up your own AWS Config rules or even use CloudFormation Drift Detection - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html

For the latter we offer many managed services (AWS Config, AWS Security Hub etc.) and also a wide variety of partner offerings (Cloud Custodian, Cloud Conformity etc.) which are available via the AWS Marketplace.

**Comment by srijitm** [comment]
So looking at the [devsecops-workshop-on-aws ](https://github.com/aws-samples/devsecops-workshop-on-aws), you can add cfn-validate-template, cfn_nag and taskcat in either your build or deploy stages. You just have to install and call the applications in build.sh or deploy.sh. 

The other option is to add a test stage which executes test.sh and you can include your tests in there. We are tracking this request here: #19 Note: You will still have to provide the commands to be executed in the test stage. Today you can include them in either the build or deploy stages.
