### ISSUE TITLE
Support for Bitbucket cloud for code source

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#22]
I used this CI/CD and tweaked it to connect BitBucket cloud for code source by using BitBucketSourceAction. I think it would be useful to support it as part of this pipeline as well. Will need to store connection ARN as well which could be stored in SSM itself.
```

   const sourceAction = new BitBucketSourceAction({
        actionName: 'BitbucketSource',
        owner: 'admin',
        repo: repoName,
        output: sourceOutputArtifact,
        connectionArn: 'arn:aws:codestar-connections:us-west-2:blablabla',
    }) 
```

Also, is it correct to use 
import { Repository } from '@aws-cdk/aws-codecommit'

for BitBucket repository as well?

   ```
 const bitBucketRepo = Repository.fromRepositoryName(
      scope,
      `${repoName}${repoBranch}BitBucketRepo`,
      repoName
    )
```

**Comment by srijitm** [comment]
Please take a look at #40 

This adds support for Github and BitBucket should be something similar.
