### ISSUE TITLE
Stack deletion using cdk destroy did not delete s3 bucket

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#23]
It leaves the s3 bucket and then fails the deploy command next time erring on the existence of the s3 bucket already

**Comment by srijitm** [comment]
Will update the documentation. Cloudformation does not support deletion of non-empty buckets.

**Comment by s1mrankaur** [comment]
@srijitm
Two ways I think this can be done:
1. remove the objects in S3 buckets and then delete the bucket?
2. Use a cdk construct (https://www.npmjs.com/package/@mobileposse/auto-delete-bucket)

**Comment by srijitm** [comment]
Right. I'm not sure it is a good idea to delete user data without their explicit understanding of the implications. The artifacts bucket can be used to store other files as well and it would be impossible for us to determine what should be removed and what should not. I rather have users implement this in their own environment than it being offered out of the box. 

I'll update the documentation to point to this discussion so users can see your feedback. Of course if enough people want this enabled by default we will revisit it.

**Comment by sumitnagpal-mck** [comment]
> Will update the documentation. Cloudformation does not support deletion of non-empty buckets.

Even an empty S3 bucket does not get deleted via cdk destroy.
