### ISSUE TITLE
Gate and control points to check who can deploy to each of the AWS accounts 

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#25]
In this CI/CD pipeline,  What's the best way to control who can trigger pipelines for dev, test, and master branch?

**Comment by srijitm** [comment]
The aws-simple-cicd project provides a framework to setup CICD using AWS services. Adding gates or only allow manual releases goes against the core tenets of CD. 
You can set up IAM policies to limit access to pipelines and any manual steps.

Please feel free to fork this project any make any changes you need to fit your use-case.
