### ISSUE TITLE
Specific test types in different stages of the pipeline

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#27]
I see that we now have a test stage in the CI/CD pipeline. Thank you so much for adding it. I plan to run unit and integration tests before deployment,  smoke tests in the dev account only, when smoke tests are positive, promote to QA env. If regression tests in QA env. are positive, promote to production.

To work those steps with this CI/CD,  how can these phases run stage-specific tests be added here? Would be great to see it in this pipeline or an example for the same.

**Comment by srijitm** [comment]
You can include the execution commands for your tests in the deploy.sh script to be executed once the deployment is complete. An environment variable 'TARGET_ENV' is available in every deployment stage. I would leverage that to determine which environment the deployment is running against and execute the appropriate set of tests.

![Screen Shot 2020-11-24 at 7 54 24 AM](https://user-images.githubusercontent.com/4087874/100097273-774d7080-2e2a-11eb-9b0b-93e73dcabbc6.png)
