### ISSUE TITLE
Pull request and merge actions in CI/CD

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#29]
There are pipelines deployed for the following branches: `development`, `master`. The respective pipeline is triggered `onCommit` event `(codeCommitRepo.onCommit('OnCommit', {})`  so whenever there is any code push to the branch. We are planning to use git-flow as the branching strategy but don't exactly see the advantages of having another branch called `staging`, in addition to `development`, `master`. 

1. Is there a use of having a third branch like "staging" when using CI/CD?
2. At what stage should the PR from the feature branch be created? 
3. At what stage should the PR be merged into the development branch?
4. At what stage should the PR from the development branch to master be created? 
4. At what stage should the PR be merged into the master branch?
5. What if the development pipeline fails? Should the code be manually unmerged to get development back in the stable condition?
6. What if the master pipeline fails? 

I would like to understand what the flow should look like starting from a feature branch.  (Also, Not looking to use Trunk based branching strategy)

**Comment by srijitm** [comment]
The aws-simple-cicd project provides a framework to setup CICD using AWS services. 

This question is specific to workflows you are looking to implement for your organization/team. This primarily depends on your organizations culture. There are many resources available which can walk you through the various options/best practices for setting up gitflow. 

Please feel free to fork this project any make any changes you need to fit your use-case.
