### ISSUE TITLE
When the pipeline fails

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#30]
Consider the following scenario:

1. Merge requested accepted to develop branch
2. The develop branch pipeline gets triggers
3. Pipeline fails due to failed or test

Now, what should the next step be here? Is reverting the code manually from the develop branch the only option as other developers in the team want to push the code and trigger the pipeline?

**Comment by srijitm** [comment]
The aws-simple-cicd project provides a framework to setup CICD using AWS services. 

This question is specific to workflows you are looking to implement for your organization/team. This primarily depends on your organizations culture. There are many resources available which can walk you through the various options/best practices for setting up gitflow. 

Please feel free to fork this project any make any changes you need to fit your use-case.
