### ISSUE TITLE
Integrating AWS CDK pipeline to deploy Serverless framework based application

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#31]
Is there any necessary integration required to use this CI/CD pipeline for deploying a Serverless framework-based application? I stumbled on https://serverless-stack.com/chapters/using-aws-cdk-with-serverless-framework.html and wondering if this is relevant here?

**Comment by srijitm** [comment]
This solutions allows you to leverage shell scripts. As long as the pre-requisites are available in the [CodeBuild image](https://aws.amazon.com/blogs/devops/extending-aws-codebuild-with-custom-build-environments/) or installed as part of the provided build.sh/deploy.sh any framework should work.

**Comment by s1mrankaur** [comment]
@srijitm  Thanks for your response. Also, how can this be used for single service deployments?
