### ISSUE TITLE
How can single service deployments be done with this CI/CD

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#33]
I would like to know how can single service deployments be done with this CI/CD.

Also, really like CDK and this CI/CD so far :)

**Comment by srijitm** [comment]
Can you provide some more context around "single service deployments"?

**Comment by s1mrankaur** [comment]
@srijitm  So let's say :

we have microservices with self-contained resources.

Auction service

Auth service

Notification service

Auction service depends on Auth service for authorization and notification service for mails. Similarly, notification service depends on auth service for authorization.

How should the deployment of these work using this CI/CD given they are self-contained but also refer to other microservices in some way so the order of deployment will matter

**Comment by srijitm** [comment]
Your question is more about orchestration of microservices and is not related to CICD. Each of the individual services should be resilient enough to start up and notify the user if a downstream service is unavailable. The CICD platform should not care about the dependencies between these services.

**Comment by s1mrankaur** [comment]
@srijitm  But is it not that the CI/CD will have to deploy the downstream services first? For example: If the CI-CD is deploying application for the first time, we nee to make sure that downstream services get deployed first

**Comment by srijitm** [comment]
@s1mrankaur no, not necessarily. You can choose to add that complexity to your release system, or design your applications to be more resilient and handle outages in other services. One of the core tenets of microservices are they they should be independently deployable.
