### ISSUE TITLE
resource access to secrets manager for bitbucket sourceaction

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#34]
```
    // SourceAction
    const sourceAction = new BitBucketSourceAction({
        actionName: 'BitbucketSource',
        owner: 'ownername',
        repo: repoName,
        output: sourceOutputArtifact,
        connectionArn: SecretValue.secretsManager('BBCloudConnection').toString(),
    })

```

This is what the source action looks like. I need it to be able to access connectionArn from SecretValue. It fails due to lack of permissions at the moment. Where should the resource permission be added?

Action in deploymentPolicy looks as follows:

  ```
          Action:
              - 'cloudformation:*'
              - 'iam:*'
              - 'lambda:*'
              - 'ecs:*'
              - 'ecr:*'
              - 'logs:*'
              - 'ec2:*'
              - 'ssm:*'
              - 'secretsmanager:*'
```

i.e have added 'secretsmanager:*' at the bottom

As of now, I get the following error if I use secretsManager:

` 17/49 | 2:14:10 a.m. | CREATE_FAILED        | AWS::IAM::Policy            | backend--854-pipeline-backend-setup-pipeline/Source/BitbucketSource/CodePipelineActionRole/DefaultPolicy (backendVLNCC854pipelinebackendsetuppipelineSourceBitbucketSourceCodePipelineActionRoleDefaultPolicy41F7C61D) Syntax errors in policy. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 62b6fb1c-77b0-432c-b907-2e409ff7c538; Proxy: null)`

The secret manager was created manually on console and has the following resource permissions:
```

{
  "Version" : "2012-10-17",
  "Statement" : [ {
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "arn:aws:iam::1111111111:role/deployment-role"
    },
    "Action" : "secretsmanager:GetSecretValue",
    "Resource" : "*"
  } ]
}
```

**Comment by srijitm** [comment]
The policy you modified is for deployments. You need to create an IAM Role which will be used by the BitBucketSourceAction. 

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.BitBucketSourceAction.html

**Comment by s1mrankaur** [comment]
@srijitm  Did you mean that I pass in a role here as NEW_ROLE with a policy that allows access to secret manager and that it will be automatically created by the CDK? 

    const sourceAction = new BitBucketSourceAction({
        actionName: 'BitbucketSource',
        owner: 'vlncc',
        repo: repoName,
        output: sourceOutputArtifact,
        branch: repoBranch,
        connectionArn: "arn:aws:codestar-connections:us-west-2:936158790285:connection/147ab0f3-bce9-499d-991f-28ac5698a8cc",
        role: NEW_ROLE
    })

**Comment by srijitm** [comment]
You won't even have to set the role. See the Github support that has been added.
