### ISSUE TITLE
pre-build phase in buildspec.yml

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#37]
To add the pre-build phase, should an additional shell script file be enough in the source codebase directory named as pre-build.sh and following in build-project.ts

```
      buildSpec: BuildSpec.fromObject({
        version: '0.2',
        phases: {
          install: {
            'runtime-versions': {
              nodejs: '10'
            }
          },
          pre-build: {
            commands: [
              'bash ${CODEBUILD_SRC_DIR}/scripts/pre-build.sh'
            ]
          },
          build: {
            commands: [
              'bash ${CODEBUILD_SRC_DIR}/scripts/build.sh'
            ]
          }
        },
```

Is there anything else that would be required?

**Comment by srijitm** [comment]
Yes, if for some reason adding it in build.sh does not make sense you can do this. This support will not be added to this project. This is because the main goal of this project is to hide away the complexities of a buildspec from developers.
