### ISSUE TITLE
Muti-region deployments for compliance and fail-over

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#38]
How can this pipeline be adopted for multi-region deployments? The reason for adopting multi-region deployment is both compliance and fail-over

**Comment by srijitm** [comment]
The only way I see this happening today is as follows:
1. Add pipeline stages which deploy to Prod-Canada, Prod-us-east-1 etc.
2. Add an environment variable which defines region
3. This environment variable will be available to deploy.sh. In your deploy.sh use this env var to target appropriate region within the target account.

**Comment by srijitm** [comment]
Leaving this as a todo for specific use-cases. The framework provides enough flexibility to achieve this.
