### ISSUE TITLE
How to integrate this pipeline with repository for end to end tests

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#43]
If the end to end tests/system tests are stored in a separate repo, how to modify this pipeline to run end to end tests on every deployment?

2.Feature request to trigger an alarm when a test fails and fail the deployment

**Comment by srijitm** [comment]
- This complexity needs to be managed on your end and is out of scope for this projects. A simple solution would be to perform a git clone in test.sh to get the source code.
- If test.sh exists with a non-zero exit code the pipeline will fail and not proceed with deployments.
