### ISSUE TITLE
Adding a new stack in cicd.ts

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#45]
The pipeline is currently deployed with the stacks that come defined at part of this CI-CD in cicd.ts file. I need to introduce a new stack that will be linked to a different repository. 

In config/config.ts, I have added

`  Tests: Array<ProjectRepo>`

In project-config.json, I have added:
```

    "Tests": [
      {
        "pipelineName": "tests",
        "ccRepoName": "tests",
        "branch": "master",
        "type": "BitBucket",
        "cron": ""
      },
      {
        "pipelineName": "tests",
        "ccRepoName": "tests",
        "branch": "develop",
        "type": "BitBucket",
        "cron": ""
      }
    ],
```
In cicd.ts, I have added:

`new CicdStack(app, 'QARepo', { prefix, ssmRoot, cicdRoleName, repos: config.Tests})
`
In package.json, I have changed the `synth` command to include the new stack:

    "synth": "npm run build && npm run cdk -- synth VLNCC-CICD-BackendRepo &&  npm run cdk -- synth QARepo"

When I try to run:

 cdk deploy --all --profile cicd

I get:

Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment.

I did also try running the command

`npm run synth
`
before the ` cdk deploy --all --profile cicd` command. 

How do I deploy the new stack?

**Comment by srijitm** [comment]
Is your AWS CLI configured correctly? Do you have a profile called CICD in the config file?

**Comment by simran66** [comment]
@srijitm  The profile is configured correctly and works alright. Had to run cdk diff command for it to see the new stack.
