### ISSUE TITLE
How to run sls deploy in the deployment when MFA is enabled

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#46]
sls deploy command that we use to deploy our services asks for MFA code. How should that be handled in this CI/CD pipeline? Different AWS accounts will need to use different profiles and will ask for MFA code each time sls deploy command needs to run.

**Comment by srijitm** [comment]
For CICD you should not be using MFA. The goal of CICD is automation. I would rely on robust IAM roles and cross-account trust relationships.
