### ISSUE TITLE
Update stack deployment order for dependencies

### ISSUE THREAD

**Issue by srijitm** [awslabs/aws-simple-cicd#52]

**Comment by skashmeri** [comment]
need to do something like this:
`new S3Stack(app, 'AWS-Simple-CICD-00-S3', { prefix, ssmRoot })
new EmailHandlerStack(app, 'AWS-Simple-CICD-01-EmailHandler', { prefix, ssmRoot })
new SemverHandlerStack(app, 'AWS-Simple-CICD-02-SemverHandler', { prefix, ssmRoot })
new CicdStack(app, 'AWS-Simple-CICD-03-Pipeline', { prefix, ssmRoot, cicdRoleName, repos: config.simpleCicd})
new CicdStack(app, 'AWS-Simple-CICD-TeamOne', { prefix, ssmRoot, cicdRoleName, repos: config.teamOne})`
