### ISSUE TITLE
How to connect to private npm registry nexus from code-pipeline

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#59]
npm install command fails in my pipeline written using aws-cdk with the following error:

`npm ERR! code ENOTFOUND   33 npm ERR! syscall getaddrinfo   34 npm ERR! errno ENOTFOUND   35 npm ERR! network request to http://nexus.company.com:8081/nexus/repository/npm-group/zip-stream/-/zip-stream-4.1.0.tgz failed, reason: getaddrinfo ENOTFOUND nexus.company.com`

How can this be fixed? npm run command works okay in my local system,

.npmrc file looks as follows:
`
registry="http://nexus.company.com:8081/nexus/repository/npm-group/"`
How to whitelist access to private registry from the pipeline?

**Comment by srijitm** [comment]
@s1mrankaur Do you have access to your on-premises servers from AWS (VPN, DirectConnect etc.?) By default you will not be able to access on-premises resources. 

You have a couple of options:
1. Set up connectivity between AWS account and on-premises.
2. If this already exists, the run your CodeBuild jobs inside of a VPC which has routes defined to on-premises.
3. Use CodeArtifact to have a mirror of your on-premises Nexus NPM repository and allow CodeBuild to pull/push artifacts from/to CodeArtifact.

**Comment by s1mrankaur** [comment]
@srijitm  CodeArtifact sounds like the solution. Ideally didn't want to have a VPN only to connect with nexus. Thanks much
