### ISSUE TITLE
Dev testing and Pull requests 

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#8]
1. How do we deploy feature branches in this pipeline?
2. According to this pipeline, when will the pull requests be accepted and merged?

**Comment by srijitm** [comment]
1. In the current implementation, you will need to update the project-config.json file and specify the branch. That will generate a Pipeline for the specified branch.
2. PR acceptance/merging is handled by the source control system e.g. CodeCommit.

**Comment by s1mrankaur** [comment]
@srijitm Thanks for your response. 

1. I need to replace CodeCommit with Bitbucket Cloud. Where all do I need to make changes to that?
2. Is the pipeline triggered on push or merge actions in the repo? Could you explain the behaviour in a bit more detail here? For ex:

1. What happens when code is pushed to a feature branch?
2. What happens when code is merged into development branch?
3. What happens when code is merged into master branch?
4. What happens when a pull request is approved?

**Comment by srijitm** [comment]
1. Build a pipeline for the CICD project as well. Then your CICD pipelines will be deployed just like any other application. 
2. See the other issue you opened. 
3. Yes, the grouping is to separate projects by team. It also generates a separate cloudformation stack per team which makes it cleaner.

Today, the pipeline is only triggered if there is a push to a specific branch (as defined in project-config.json).

**Comment by s1mrankaur** [comment]
@srijitm Thanks for your response. Is it right to assume that the pipeline is triggered by the merge event as well?

**Comment by srijitm** [comment]
Yes, any updates to master (or the branch specified) will trigger the pipeline.
