### ISSUE TITLE
Replacing codecommit with bitbucket and trigger types for the pipeline

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#9]
How can CodeCommit be replaced with BitBucket cloud repo for source? What exact changes are required to fit in this pipeline?

**Comment by srijitm** [comment]
To support other source repositories I would define a new pipeline here: https://github.com/awslabs/aws-simple-cicd/blob/master/lib/pipelines/

Then based on the "type" in project-config.json the appropriate pipeline library will be used.
